/*
 * This file was generated by dbusidl2cpp version 0.6
 * Command line was: dbusidl2cpp -m -a ksmserveradaptor -- org.kde.ksmserver.KSmserver.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef KSMSERVERADAPTOR_H_182991151064542
#define KSMSERVERADAPTOR_H_182991151064542

#include <QtCore/QObject>
#include <dbus/qdbus.h>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.kde.ksmserver.KSmserver
 */
class KSmserverAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.ksmserver.KSmserver")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.ksmserver.KSmserver\" >\n"
"    <method name=\"logout\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"confirm\" />\n"
"      <arg direction=\"in\" type=\"i\" name=\"sdtype\" />\n"
"      <arg direction=\"in\" type=\"i\" name=\"sdmode\" />\n"
"    </method>\n"
"    <method name=\"restoreSessionInternal\" />\n"
"    <method name=\"restoreSessionDoneInternal\" />\n"
"    <method name=\"sessionList\" >\n"
"      <arg direction=\"out\" type=\"as\" />\n"
"    </method>\n"
"    <method name=\"currentSession\" >\n"
"      <arg direction=\"out\" type=\"s\" />\n"
"    </method>\n"
"    <method name=\"saveCurrentSession\" />\n"
"    <method name=\"saveCurrentSessionAs\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\" />\n"
"    </method>\n"
"    <method name=\"autoStart2\" />\n"
"    <method name=\"suspendStartup\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\" />\n"
"    </method>\n"
"    <method name=\"resumeStartup\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\" />\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    KSmserverAdaptor(QObject *parent);
    virtual ~KSmserverAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void autoStart2();
    QString currentSession();
    void logout(int confirm, int sdtype, int sdmode);
    void restoreSessionDoneInternal();
    void restoreSessionInternal();
    void resumeStartup(const QString &name);
    void saveCurrentSession();
    void saveCurrentSessionAs(const QString &name);
    QStringList sessionList();
    void suspendStartup(const QString &name);
Q_SIGNALS: // SIGNALS
};

#endif
