IF (KEPHAL_INCLUDE_DIR AND KEPHAL_LIBRARY)
   SET(Kephal_FIND_QUIETLY TRUE)
ENDIF (KEPHAL_INCLUDE_DIR AND KEPHAL_LIBRARY)

FIND_PATH(KEPHAL_INCLUDE_DIR NAMES kephal/screens.h PATHS
        ${KDE4_INCLUDE_DIR}
        ${INCLUDE_INSTALL_DIR})

FIND_LIBRARY(KEPHAL_LIBRARY NAMES kephal PATHS
        ${KDE4_LIB_DIR}
        ${LIB_INSTALL_DIR})

IF (KEPHAL_INCLUDE_DIR AND KEPHAL_LIBRARY)
   SET(KEPHAL_FOUND TRUE)
ENDIF (KEPHAL_INCLUDE_DIR AND KEPHAL_LIBRARY)


IF (KEPHAL_FOUND)
   IF (NOT Kephal_FIND_QUIETLY)
      MESSAGE(STATUS "Found Kephal: ${KEPHAL_LIBRARY}")
   ENDIF (NOT Kephal_FIND_QUIETLY)
ELSE (KEPHAL_FOUND)
   IF (Kephal_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find Kephal")
   ENDIF (Kephal_FIND_REQUIRED)
ENDIF (KEPHAL_FOUND)
