#!/bin/sh
# Installs a KDE theme (into the user's theme dir)
appsdir=`kde4-config --path data | sed -e 's/:.*//'`
themedir=$appsdir"/kthememanager/themes/"`basename "$1" ".kth"`
if test -n "$appsdir"; then
  test -d "$themedir" || mkdir -p "$themedir"
  #echo "$themedir"
  cp -f "$1" "$themedir"
  cd "$themedir"
  tarball=`basename "$1"`
  #echo $tarball
  tar xzf "$tarball"
  rm -f "$tarball"
fi
