FIND_PATH(KEPHAL_INCLUDE_DIR kephal/screens.h /usr/include /usr/local/include)

FIND_LIBRARY(KEPHAL_LIBRARY NAMES kephal PATH /usr/lib /usr/local/lib)

IF (KEPHAL_INCLUDE_DIR AND KEPHAL_LIBRARY)
   SET(KEPHAL_FOUND TRUE)
ENDIF (KEPHAL_INCLUDE_DIR AND KEPHAL_LIBRARY)


IF (KEPHAL_FOUND)
   IF (NOT Kephal_FIND_QUIETLY)
      MESSAGE(STATUS "Found Kephal: ${KEPHAL_LIBRARY}")
   ENDIF (NOT Kephal_FIND_QUIETLY)
ELSE (KEPHAL_FOUND)
   IF (Kephal_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find Kephal")
   ENDIF (Kephal_FIND_REQUIRED)
ENDIF (KEPHAL_FOUND)
