/*
 * This file was generated by dbusidl2cpp version 0.6
 * Command line was: dbusidl2cpp -c KSplashAdaptor -m -a ksplashadaptor -- org.kde.KSplash.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef KSPLASHADAPTOR_H_52921151345280
#define KSPLASHADAPTOR_H_52921151345280

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.kde.KSplash
 */
class KSplashAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.KSplash")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.KSplash\" >\n"
"    <method name=\"upAndRunning\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"component\" />\n"
"    </method>\n"
"    <method name=\"setMaxProgress\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"percent\" />\n"
"    </method>\n"
"    <method name=\"setStartupItemCount\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"count\" />\n"
"    </method>\n"
"    <method name=\"programStarted\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"programIcon\" />\n"
"      <arg direction=\"in\" type=\"s\" name=\"programName\" />\n"
"      <arg direction=\"in\" type=\"s\" name=\"description\" />\n"
"    </method>\n"
"    <method name=\"startupComplete\" />\n"
"    <method name=\"close\" />\n"
"  </interface>\n"
        "")
public:
    KSplashAdaptor(QObject *parent);
    virtual ~KSplashAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void close();
    void programStarted(const QString &programIcon, const QString &programName, const QString &description);
    void setMaxProgress(int percent);
    void setStartupItemCount(int count);
    void startupComplete();
    void upAndRunning(const QString &component);
Q_SIGNALS: // SIGNALS
};

#endif
