/*
 * This file was generated by dbusidl2cpp version 0.4
 * when processing input file org.kde.ksplash.KSplash.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 */

#ifndef KSPLASHADAPTOR_H_318971149495986
#define KSPLASHADAPTOR_H_318971149495986

#include <QtCore/QObject>
#include <dbus/qdbus.h>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.kde.ksplash.KSplash
 */
class KSplashAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.ksplash.KSplash")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.ksplash.KSplash\" >\n"
"    <method name=\"upAndRunning\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"component\" />\n"
"    </method>\n"
"    <method name=\"setMaxProgress\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"percent\" />\n"
"    </method>\n"
"    <method name=\"setStartupItemCount\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"count\" />\n"
"    </method>\n"
"    <method name=\"programStarted\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"programIcon\" />\n"
"      <arg direction=\"in\" type=\"s\" name=\"programName\" />\n"
"      <arg direction=\"in\" type=\"s\" name=\"description\" />\n"
"    </method>\n"
"    <method name=\"startupComplete\" />\n"
"    <method name=\"close\" />\n"
"  </interface>\n"
        "")
public:
    KSplashAdaptor(QObject *parent);
    virtual ~KSplashAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void close();
    void programStarted(const QString &programIcon, const QString &programName, const QString &description);
    void setMaxProgress(int percent);
    void setStartupItemCount(int count);
    void startupComplete();
    void upAndRunning(const QString &component);
Q_SIGNALS: // SIGNALS
};

#endif
