
#!/usr/bin/env python
# Generated by pykdeuic4 from timezonesConfig.ui on Sun Sep 14 13:02:53 2008
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_timezonesConfig(object):
    def setupUi(self, timezonesConfig):
        timezonesConfig.setObjectName("timezonesConfig")
        timezonesConfig.resize(308, 227)
        self.vboxlayout = QtGui.QVBoxLayout(timezonesConfig)
        self.vboxlayout.setObjectName("vboxlayout")
        self.localTimeZone = QtGui.QCheckBox(timezonesConfig)
        self.localTimeZone.setObjectName("localTimeZone")
        self.vboxlayout.addWidget(self.localTimeZone)
        self.timeZones = KTimeZoneWidget(timezonesConfig)
        self.timeZones.setMinimumSize(QtCore.QSize(300, 150))
        self.timeZones.setObjectName("timeZones")
        self.vboxlayout.addWidget(self.timeZones)

        self.retranslateUi(timezonesConfig)
        QtCore.QObject.connect(self.localTimeZone, QtCore.SIGNAL("toggled(bool)"), self.timeZones.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(timezonesConfig)

    def retranslateUi(self, timezonesConfig):
        self.localTimeZone.setText(kdecore.i18n("Use &local time zone"))
        self.timeZones.headerItem().setText(0, kdecore.i18n("Area"))
        self.timeZones.headerItem().setText(1, kdecore.i18n("Region"))
        self.timeZones.headerItem().setText(2, kdecore.i18n("Comment"))

from PyKDE4.kdeui import KTimeZoneWidget
