/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -N -m -p mm-modem-gsm-hsointerface introspection/mm-modem-gsm-hso.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "mm-modem-gsm-hsointerface.h"

/*
 * Implementation of interface class OrgFreedesktopModemManagerModemGsmHsoInterface
 */

OrgFreedesktopModemManagerModemGsmHsoInterface::OrgFreedesktopModemManagerModemGsmHsoInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopModemManagerModemGsmHsoInterface::~OrgFreedesktopModemManagerModemGsmHsoInterface()
{
}


#include "mm-modem-gsm-hsointerface.moc"
