/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -N -m -p mm-modem-gsm-ussdinterface introspection/mm-modem-gsm-ussd.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef MM_MODEM_GSM_USSDINTERFACE_H
#define MM_MODEM_GSM_USSDINTERFACE_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.freedesktop.ModemManager.Modem.Gsm.Ussd
 */
class OrgFreedesktopModemManagerModemGsmUssdInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freedesktop.ModemManager.Modem.Gsm.Ussd"; }

public:
    OrgFreedesktopModemManagerModemGsmUssdInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~OrgFreedesktopModemManagerModemGsmUssdInterface();

    Q_PROPERTY(QString NetworkNotification READ networkNotification)
    inline QString networkNotification() const
    { return qvariant_cast< QString >(property("NetworkNotification")); }

    Q_PROPERTY(QString NetworkRequest READ networkRequest)
    inline QString networkRequest() const
    { return qvariant_cast< QString >(property("NetworkRequest")); }

    Q_PROPERTY(QString State READ state)
    inline QString state() const
    { return qvariant_cast< QString >(property("State")); }

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> Cancel()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("Cancel"), argumentList);
    }

    inline QDBusPendingReply<QString> Initiate(const QString &command)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(command);
        return asyncCallWithArgumentList(QLatin1String("Initiate"), argumentList);
    }

    inline QDBusPendingReply<> Respond(const QString &response)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(response);
        return asyncCallWithArgumentList(QLatin1String("Respond"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

#endif
