/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -N -m -p mm-modeminterface introspection/mm-modem.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "mm-modeminterface.h"

/*
 * Implementation of interface class OrgFreedesktopModemManagerModemInterface
 */

OrgFreedesktopModemManagerModemInterface::OrgFreedesktopModemManagerModemInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopModemManagerModemInterface::~OrgFreedesktopModemManagerModemInterface()
{
}


#include "mm-modeminterface.moc"
