include(${config})

if(NOT altLighterColor)
   set(altLighterColor ${lighterColor})
endif(NOT altLighterColor)
if(NOT altMediumColor)
   set(altMediumColor ${mediumColor})
endif(NOT altMediumColor)
if(NOT altDarkerColor)
   set(altDarkerColor ${darkerColor})
endif(NOT altDarkerColor)

file(READ "${input}" contents)
string(REPLACE "#ff80ff;" "${lighterColor};" contents "${contents}")
string(REPLACE "#804080;" "${mediumColor};" contents "${contents}")
string(REPLACE "#201020;" "${darkerColor};" contents "${contents}")
string(REPLACE "#c080ff;" "${altLighterColor};" contents "${contents}")
string(REPLACE "#604080;" "${altMediumColor};" contents "${contents}")
string(REPLACE "#181020;" "${altDarkerColor};" contents "${contents}")
file(WRITE "${output}" "${contents}")
