/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -N -m -p nm-access-pointinterface /space/kde/sources/trunk/KDE/kdebase/workspace/solid/networkmanager-0.7/dbus/introspection/nm-access-point.xml
 *
 * dbusxml2cpp is Copyright (C) 2006 Trolltech ASA. All rights reserved.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef NM_ACCESS_POINTINTERFACE_H_1207683005
#define NM_ACCESS_POINTINTERFACE_H_1207683005

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.freedesktop.NetworkManager.AccessPoint
 */
class OrgFreedesktopNetworkManagerAccessPointInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freedesktop.NetworkManager.AccessPoint"; }

public:
    OrgFreedesktopNetworkManagerAccessPointInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~OrgFreedesktopNetworkManagerAccessPointInterface();

    Q_PROPERTY(uint Flags READ flags)
    inline uint flags() const
    { return qvariant_cast< uint >(internalPropGet("Flags")); }

    Q_PROPERTY(uint Frequency READ frequency)
    inline uint frequency() const
    { return qvariant_cast< uint >(internalPropGet("Frequency")); }

    Q_PROPERTY(QString HwAddress READ hwAddress)
    inline QString hwAddress() const
    { return qvariant_cast< QString >(internalPropGet("HwAddress")); }

    Q_PROPERTY(uint MaxBitrate READ maxBitrate)
    inline uint maxBitrate() const
    { return qvariant_cast< uint >(internalPropGet("MaxBitrate")); }

    Q_PROPERTY(int Mode READ mode)
    inline int mode() const
    { return qvariant_cast< int >(internalPropGet("Mode")); }

    Q_PROPERTY(uint RsnFlags READ rsnFlags)
    inline uint rsnFlags() const
    { return qvariant_cast< uint >(internalPropGet("RsnFlags")); }

    Q_PROPERTY(QByteArray Ssid READ ssid)
    inline QByteArray ssid() const
    { return qvariant_cast< QByteArray >(internalPropGet("Ssid")); }

    Q_PROPERTY(uchar Strength READ strength)
    inline uchar strength() const
    { return qvariant_cast< uchar >(internalPropGet("Strength")); }

    Q_PROPERTY(uint WpaFlags READ wpaFlags)
    inline uint wpaFlags() const
    { return qvariant_cast< uint >(internalPropGet("WpaFlags")); }

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void PropertiesChanged(const QVariantMap &properties);
};

#endif
