/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -N -m -p nm-device-serialinterface /space/kde/sources/trunk/KDE/kdebase/workspace/solid/networkmanager-0.7/dbus/introspection/nm-device-serial.xml
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "nm-device-serialinterface.h"

/*
 * Implementation of interface class OrgFreedesktopNetworkManagerDeviceSerialInterface
 */

OrgFreedesktopNetworkManagerDeviceSerialInterface::OrgFreedesktopNetworkManagerDeviceSerialInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopNetworkManagerDeviceSerialInterface::~OrgFreedesktopNetworkManagerDeviceSerialInterface()
{
}


#include "nm-device-serialinterface.moc"
