// This file is generated by kconfig_compiler from oxygenshadow.kcfg.
// All changes you do to this file will be lost.

#include "oxygenshadowconfigdata.h"

namespace Oxygen
{
    ShadowConfigData::ShadowConfigData( const QString& group )
        : KConfigSkeleton( QLatin1String( "oxygenrc" ) )
    {
        setCurrentGroup( group );

        KConfigSkeleton::ItemColor  *itemInnerColor;
        itemInnerColor = new KConfigSkeleton::ItemColor( currentGroup(), QLatin1String( "InnerColor" ), mInnerColor, QColor( 0,0,0 ) );
        addItem( itemInnerColor, QLatin1String( "InnerColor" ) );
        KConfigSkeleton::ItemColor  *itemOuterColor;
        itemOuterColor = new KConfigSkeleton::ItemColor( currentGroup(), QLatin1String( "OuterColor" ), mOuterColor, QColor( 0,0,0 ) );
        addItem( itemOuterColor, QLatin1String( "OuterColor" ) );
        KConfigSkeleton::ItemInt  *itemSize;
        itemSize = new KConfigSkeleton::ItemInt( currentGroup(), QLatin1String( "Size" ), mSize, 25 );
        addItem( itemSize, QLatin1String( "Size" ) );
        KConfigSkeleton::ItemBool  *itemUseOuterColor;
        itemUseOuterColor = new KConfigSkeleton::ItemBool( currentGroup(), QLatin1String( "UseOuterColor" ), mUseOuterColor, false );
        addItem( itemUseOuterColor, QLatin1String( "UseOuterColor" ) );
        KConfigSkeleton::ItemDouble  *itemVerticalOffset;
        itemVerticalOffset = new KConfigSkeleton::ItemDouble( currentGroup(), QLatin1String( "VerticalOffset" ), mVerticalOffset, 0.2 );
        addItem( itemVerticalOffset, QLatin1String( "VerticalOffset" ) );
    }

    ShadowConfigData::~ShadowConfigData()
    {
    }

}
