/*
 * This file was generated by dbusidl2cpp version 0.6
 * Command line was: dbusidl2cpp -c KCMInitAdaptor -m -a kcminitadaptor -- org.kde.KCMInit.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef KCMINITADAPTOR_H_43001151344705
#define KCMINITADAPTOR_H_43001151344705

#include <QtCore/QObject>
#include <dbus/qdbus.h>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.kde.KCMInit
 */
class KCMInitAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.KCMInit")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.KCMInit\" >\n"
"    <method name=\"runPhase1\" />\n"
"    <method name=\"runPhase2\" />\n"
"  </interface>\n"
        "")
public:
    KCMInitAdaptor(QObject *parent);
    virtual ~KCMInitAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void runPhase1();
    void runPhase2();
Q_SIGNALS: // SIGNALS
};

#endif
