/*
 * This file was generated by dbusidl2cpp version 0.6
 * Command line was: dbusidl2cpp -c KCMInitAdaptor -m -a kcminitadaptor -- org.kde.KCMInit.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "kcminitadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class KCMInitAdaptor
 */

KCMInitAdaptor::KCMInitAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

KCMInitAdaptor::~KCMInitAdaptor()
{
    // destructor
}

void KCMInitAdaptor::runPhase1()
{
    // handle method call org.kde.KCMInit.runPhase1
    QMetaObject::invokeMethod(parent(), "runPhase1");

    // Alternative:
    //static_cast<YourObjectType *>(parent())->runPhase1();
}

void KCMInitAdaptor::runPhase2()
{
    // handle method call org.kde.KCMInit.runPhase2
    QMetaObject::invokeMethod(parent(), "runPhase2");

    // Alternative:
    //static_cast<YourObjectType *>(parent())->runPhase2();
}


#include "kcminitadaptor.moc"
