/*
 * This file was generated by dbusidl2cpp version 0.6
 * Command line was: dbusidl2cpp -m -a kbackgroundadaptor -c KBackgroundAdaptor -i bgmanager.h -l KBackgroundManager -- org.kde.kdesktop.Background.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef KBACKGROUNDADAPTOR_H_87041151414534
#define KBACKGROUNDADAPTOR_H_87041151414534

#include <QtCore/QObject>
#include <dbus/qdbus.h>
#include "bgmanager.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.kde.kdesktop.Background
 */
class KBackgroundAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.kdesktop.Background")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.kdesktop.Background\" >\n"
"    <method name=\"configure\" />\n"
"    <method name=\"setExport\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"xport\" />\n"
"    </method>\n"
"    <method name=\"isExport\" >\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"    <method name=\"setCommon\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"common\" />\n"
"    </method>\n"
"    <method name=\"isCommon\" >\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"    <method name=\"setCache\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"bLinit\" />\n"
"      <arg direction=\"in\" type=\"i\" name=\"size\" />\n"
"    </method>\n"
"    <method name=\"setWallpaper\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"desk\" />\n"
"      <arg direction=\"in\" type=\"s\" name=\"wallpaper\" />\n"
"      <arg direction=\"in\" type=\"i\" name=\"mode\" />\n"
"    </method>\n"
"    <method name=\"setWallpaper\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"wallpaper\" />\n"
"      <arg direction=\"in\" type=\"i\" name=\"mode\" />\n"
"    </method>\n"
"    <method name=\"changeWallpaper\" />\n"
"    <method name=\"setBackgroundEnabled\" >\n"
"      <arg direction=\"in\" type=\"b\" name=\"enable\" />\n"
"    </method>\n"
"    <method name=\"currentWallpaper\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"desk\" />\n"
"      <arg direction=\"out\" type=\"s\" />\n"
"    </method>\n"
"    <method name=\"wallpaperList\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"desk\" />\n"
"      <arg direction=\"out\" type=\"as\" />\n"
"    </method>\n"
"    <method name=\"wallpaperFiles\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"desk\" />\n"
"      <arg direction=\"out\" type=\"as\" />\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    KBackgroundAdaptor(KBackgroundManager *parent);
    virtual ~KBackgroundAdaptor();

    inline KBackgroundManager *parent() const
    { return static_cast<KBackgroundManager *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void changeWallpaper();
    void configure();
    QString currentWallpaper(int desk);
    bool isCommon();
    bool isExport();
    void setBackgroundEnabled(bool enable);
    void setCache(int bLinit, int size);
    void setCommon(int common);
    void setExport(int xport);
    void setWallpaper(const QString &wallpaper, int mode);
    void setWallpaper(int desk, const QString &wallpaper, int mode);
    QStringList wallpaperFiles(int desk);
    QStringList wallpaperList(int desk);
Q_SIGNALS: // SIGNALS
};

#endif
