/*
 * This file was generated by dbusidl2cpp version 0.6
 * Command line was: dbusidl2cpp -m -a kdesktopadaptor -c KDesktopAdaptor -i desktop.h -l KDesktop -- org.kde.kdesktop.Desktop.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef KDESKTOPADAPTOR_H_95931151420526
#define KDESKTOPADAPTOR_H_95931151420526

#include <QtCore/QObject>
#include <dbus/qdbus.h>
#include "desktop.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.kde.kdesktop.Desktop
 */
class KDesktopAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.kdesktop.Desktop")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.kdesktop.Desktop\" >\n"
"    <method name=\"runAutoStart\" />\n"
"    <method name=\"rearrangeIcons\" />\n"
"    <method name=\"lineupIcons\" />\n"
"    <method name=\"selectAll\" />\n"
"    <method name=\"unselectAll\" />\n"
"    <method name=\"refreshIcons\" />\n"
"    <method name=\"selectedURLs\" >\n"
"      <arg direction=\"out\" type=\"as\" />\n"
"    </method>\n"
"    <method name=\"configure\" />\n"
"    <method name=\"popupExecuteCommand\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"command\" />\n"
"    </method>\n"
"    <method name=\"background\" >\n"
"      <arg direction=\"out\" type=\"o\" />\n"
"    </method>\n"
"    <method name=\"screenSaver\" >\n"
"      <arg direction=\"out\" type=\"o\" />\n"
"    </method>\n"
"    <method name=\"refresh\" />\n"
"    <method name=\"logout\" />\n"
"    <method name=\"isVRoot\" >\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"    <method name=\"setVRoot\" >\n"
"      <arg direction=\"in\" type=\"b\" name=\"enable\" />\n"
"    </method>\n"
"    <method name=\"clearCommandHistory\" />\n"
"    <method name=\"isIconsEnabled\" >\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"    <method name=\"setIconsEnabled\" >\n"
"      <arg direction=\"in\" type=\"b\" name=\"enable\" />\n"
"    </method>\n"
"    <method name=\"switchDesktops\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"delta\" />\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    KDesktopAdaptor(KDesktop *parent);
    virtual ~KDesktopAdaptor();

    inline KDesktop *parent() const
    { return static_cast<KDesktop *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QDBusObjectPath background();
    void clearCommandHistory();
    void configure();
    bool isIconsEnabled();
    bool isVRoot();
    void lineupIcons();
    void logout();
    void popupExecuteCommand(const QString &command);
    void rearrangeIcons();
    void refresh();
    void refreshIcons();
    void runAutoStart();
    QDBusObjectPath screenSaver();
    void selectAll();
    QStringList selectedURLs();
    void setIconsEnabled(bool enable);
    void setVRoot(bool enable);
    void switchDesktops(int delta);
    void unselectAll();
Q_SIGNALS: // SIGNALS
};

#endif
