/*
 * This file was generated by dbusidl2cpp version 0.5
 * when processing input file org.kde.kdesktop.KScreensaver.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 */

#ifndef KSCREENSAVERADAPTOR_H_297771149867543
#define KSCREENSAVERADAPTOR_H_297771149867543

#include <QtCore/QObject>
#include <dbus/qdbus.h>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.kde.kdesktop.KScreensaver
 */
class KScreensaverAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.kdesktop.KScreensaver")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.kdesktop.KScreensaver\" >\n"
"    <method name=\"lock\" />\n"
"    <method name=\"save\" />\n"
"    <method name=\"quit\" />\n"
"    <method name=\"isEnabled\" >\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"    <method name=\"enable\" >\n"
"      <arg direction=\"in\" type=\"b\" name=\"e\" />\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"    <method name=\"isBlanked\" >\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"    <method name=\"configure\" />\n"
"    <method name=\"setBlankOnly\" >\n"
"      <arg direction=\"in\" type=\"b\" name=\"blankOnly\" />\n"
"    </method>\n"
"    <method name=\"saverLockReady\" />\n"
"  </interface>\n"
        "")
public:
    KScreensaverAdaptor(QObject *parent);
    virtual ~KScreensaverAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void configure();
    bool enable(bool e);
    bool isBlanked();
    bool isEnabled();
    void lock();
    void quit();
    void save();
    void saverLockReady();
    void setBlankOnly(bool blankOnly);
Q_SIGNALS: // SIGNALS
};

#endif
