# Generated automatically from Makefile.in by config.pl.
# KDE tags expanded automatically by am_edit - $Revision$ 
# Makefile.in generated automatically by automake 1.4 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.


SHELL = /bin/sh

srcdir = .
top_srcdir = ../../..
VPATH = .
prefix = /opt/kde
exec_prefix = ${prefix}
#>- 
bindir = $(exec_prefix)/bin
#>+ 3
DEPDIR = .deps

bindir = $(exec_prefix)/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/kdebase
pkglibdir = $(libdir)/kdebase
pkgincludedir = $(includedir)/kdebase

top_builddir = ../../..

ACLOCAL = aclocal
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /usr/bin/ginstall -c
INSTALL_PROGRAM = ${INSTALL} $(INSTALL_STRIP_FLAG) $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = i686-pc-linux-gnu
build_triplet = i686-pc-linux-gnu
host_alias = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
target_alias = i686-pc-linux-gnu
target_triplet = i686-pc-linux-gnu
AS = @AS@
AUTODIRS = 
CC = gcc
CPP = gcc -E
CXX = g++
CXXCPP = @CXXCPP@
DCOPIDL = $(kde_bindir)/dcopidl
DCOPIDL2CPP = $(kde_bindir)/dcopidl2cpp
DCOP_DEPENDENCIES = $(DCOPIDL)
DLLTOOL = @DLLTOOL@
DPMSINC = 
DPMSLIB = -lXdpms $(LIB_X11)
EXEEXT = 
EXTRA_LIBSMB_ADD = 
EXTRA_LIBSMB_FLAGS = 
GLINC = 
GLLIB = -lMesaGL -lMesaGLU $(LIB_X11)
GL_SAVERS = kmorph3d.kss kspace.kss kpipes.kss
GMSGFMT = :
IDL = @IDL@
IDL_DEPENDENCIES = @IDL_DEPENDENCIES@
KDE_CXXFLAGS = 
KDE_EXTRA_RPATH = 
KDE_INCLUDES = -I/opt/kde/include
KDE_LDFLAGS = -L/opt/kde/lib
KDE_RPATH = -R $(kde_libraries) -R $(qt_libraries) -R $(x_libraries)
KDE_USE_CLOSURE_FALSE = #
KDE_USE_CLOSURE_TRUE = 
KDE_USE_FINAL_FALSE = 
KDE_USE_FINAL_TRUE = #
KERBEROS_INCS = 
KERBEROS_LIBS = 
KERBEROS_ROOT = 
KRB_RPATH = 
LDAP_INCS = 
LDAP_LIBS = 
LDAP_RPATH = 
LDAP_SUBDIR = 
LIBALIB = 
LIBCOMPAT = 
LIBCRYPT = -lcrypt
LIBCURSES = -lncurses
LIBDL = -ldl
LIBJPEG = -ljpeg
LIBMICO = @LIBMICO@
LIBOBJS = @LIBOBJS@
LIBOSSAUDIO = 
LIBPNG = -lpng -lz -lm
LIBPTHREAD = @LIBPTHREAD@
LIBPYTHON = @LIBPYTHON@
LIBQIMGIO = @LIBQIMGIO@
LIBSM =  -lSM
LIBSOCKET = 
LIBTIFF = -ltiff -ljpeg -lz
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIBUCB = 
LIBUTEMPTER = 
LIBUTIL = -lutil
LIBXDMCP = -lXdmcp
LIBZ = -lz
LIB_KAB = -lkab
LIB_KDECORE = -lkdecore
LIB_KDEUI = -lkdeui
LIB_KFILE = -lkfile
LIB_KFM = 
LIB_KFORMULA = -lkformula
LIB_KHTML = -lkhtml
LIB_KIMGIO = -lkimgio
LIB_KIO = -lkio
LIB_KPARTS = -lkparts
LIB_KSPELL = -lkspell
LIB_KSYCOCA = -lksycoca
LIB_KWRITE = -lkwrite
LIB_LIBS = 
LIB_QT = -lqt $(LIBPNG) -lXext $(LIB_X11) $(X_PRE_LIBS)
LIB_SMB = -lsmb
LIB_X11 = -lX11 $(LIBSOCKET)
LN_S = ln -s
MAKEINFO = makeinfo
MICO_INCLUDES = @MICO_INCLUDES@
MICO_LDFLAGS = @MICO_LDFLAGS@
MOC = /opt/qt-copy//bin/moc
MOTIF_CFLAGS = 
MOTIF_LIBS = -lXm
MSGFMT = :
NOOPT_CXXFLAGS =  -fno-exceptions -fno-rtti -fno-check-new -Wall -pedantic -W -Wpointer-arith -Wmissing-prototypes -Wwrite-strings -Wno-long-long -fno-builtin
NOREPO = -fno-repo
OBJDUMP = @OBJDUMP@
OBJEXT = o
ODBC_DIR = 
PACKAGE = kdebase
PAMINC = 
PAMLIBPATHS = 
PAMLIBS = 
PASSWDLIB = 
PYTHONINC = @PYTHONINC@
PYTHONLIB = @PYTHONLIB@
QT_INCLUDES = -I/opt/qt-copy//include
QT_LDFLAGS = -L/opt/qt-copy//lib
RANLIB = ranlib
REPO = -frepo
RUN_KAPPFINDER = yes
SAMBA_LIBS = no. Falling back on native code.
SETUIDFLAGS = -m 4755
STRIP = strip
TOPSUBDIRS =  applnk doc drkonqi kappfinder kcheckpass kcontrol kdebugdialog kdesktop kdesu kdewizard kdm khelpcenter kicker kioslave konqueror konsole kscreensaver ksmserver kstart kwin kxmlrpc l10n nsplugins pics
USER_INCLUDES = 
USER_LDFLAGS = 
USE_EXCEPTIONS = -fexceptions
USE_NLS = yes
USE_RTTI = -frtti
VERSION = 2.0pre
XBINDIR = /usr/X11R6/bin
XGETTEXT = :
XPMINC = 
XPMLIB = -lXpm $(LIB_X11)
XPM_SAVERS = kbat.kss kmatrix.kss
X_EXTRA_LIBS = 
X_INCLUDES = 
X_LDFLAGS = -L/usr/X11R6/lib
X_PRE_LIBS =  -lSM -lICE
X_SERVER = /usr/X11R6/bin
ac_xdmdir = /usr/X11R6/lib/X11/xdm
all_includes = -I/opt/kde/include -I/opt/qt-copy//include  
all_libraries = -L/usr/X11R6/lib -L/opt/qt-copy//lib -L/opt/kde/lib 
idldir = @idldir@
include_motif = 
kde_appsdir = $(prefix)/share/applnk
kde_bindir = $(exec_prefix)/bin
kde_cgidir = $(exec_prefix)/cgi-bin
kde_confdir = $(prefix)/share/config
kde_datadir = $(prefix)/share/apps
kde_htmldir = $(prefix)/share/doc/HTML
kde_icondir = $(prefix)/share/icons
kde_includes = /opt/kde/include
kde_libraries = /opt/kde/lib
kde_locale = $(prefix)/share/locale
kde_mimedir = $(prefix)/share/mimelnk
kde_minidir = /dev/null
kde_servicesdir = $(prefix)/share/services
kde_servicetypesdir = $(prefix)/share/servicetypes
kde_sounddir = $(prefix)/share/sounds
kde_templatesdir = $(prefix)/share/templates
kde_toolbardir = $(prefix)/share/toolbar
kde_wallpaperdir = $(prefix)/share/wallpapers
link_motif = -lXm
micodir = @micodir@
nogroup = nogroup
qt_includes = /opt/qt-copy//include
qt_libraries = /opt/qt-copy//lib
x_includes = .
x_libraries = /usr/X11R6/lib
xdmconfigsubdir = 

KDE_ICON = AUTO
mkinstalldirs = $(SHELL) $(top_srcdir)/admin/mkinstalldirs
CONFIG_HEADER = ../../../config.h
CONFIG_CLEAN_FILES = 
DIST_COMMON =  Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = tar
GZIP_ENV = --best
#>- all: all-redirect
#>+ 1
all: docs-am  all-redirect
.SUFFIXES:
$(srcdir)/Makefile.in: Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
#>- 	cd $(top_srcdir) && $(AUTOMAKE) --gnu kcontrol/pics/hicolor/Makefile
#>+ 2
	cd $(top_srcdir) && $(AUTOMAKE) --gnu kcontrol/pics/hicolor/Makefile
	cd $(top_srcdir) && perl admin/am_edit kcontrol/pics/hicolor/Makefile.in

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status $(BUILT_SOURCES)
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status

tags: TAGS
TAGS:


distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = kcontrol/pics/hicolor

distdir: $(DISTFILES)
	here=`cd $(top_builddir) && pwd`; \
	top_distdir=`cd $(top_distdir) && pwd`; \
	distdir=`cd $(distdir) && pwd`; \
	cd $(top_srcdir) \
	  && $(AUTOMAKE) --include-deps --build-dir=$$here --srcdir-name=$(top_srcdir) --output-dir=$$top_distdir --gnu kcontrol/pics/hicolor/Makefile
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am:
install-exec: install-exec-am

#>- install-data-am:
#>+ 1
install-data-am: install-kde-icons 
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
#>- uninstall-am:
#>+ 1
uninstall-am: uninstall-kde-icons 
uninstall: uninstall-am
all-am: Makefile
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-generic mostlyclean-am

#>- clean: clean-am
#>+ 1
clean: kde-rpo-clean  clean-am

distclean-am:  distclean-generic clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-generic distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: tags distdir info-am info dvi-am dvi check check-am \
installcheck-am installcheck install-exec-am install-exec \
install-data-am install-data install-am install uninstall-am uninstall \
all-redirect all-am all installdirs mostlyclean-generic \
distclean-generic clean-generic maintainer-clean-generic clean \
mostlyclean distclean maintainer-clean


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:

#>+ 2
docs-am:

#>+ 114
install-kde-icons:
	$(mkinstalldirs) $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps
	$(INSTALL_DATA) $(srcdir)/hi32-app-icons.png $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/icons.png
	$(INSTALL_DATA) $(srcdir)/hi32-app-colors.png $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/colors.png
	$(INSTALL_DATA) $(srcdir)/hi32-app-password.png $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/password.png
	$(mkinstalldirs) $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps
	$(INSTALL_DATA) $(srcdir)/hi48-app-icons.png $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/icons.png
	$(INSTALL_DATA) $(srcdir)/hi32-app-clock.png $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/clock.png
	$(INSTALL_DATA) $(srcdir)/hi48-app-password.png $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/password.png
	$(INSTALL_DATA) $(srcdir)/hi48-app-clock.png $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/clock.png
	$(INSTALL_DATA) $(srcdir)/hi32-app-energy.png $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/energy.png
	$(INSTALL_DATA) $(srcdir)/hi32-app-fonts.png $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/fonts.png
	$(INSTALL_DATA) $(srcdir)/hi32-app-screensaver.png $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/screensaver.png
	$(INSTALL_DATA) $(srcdir)/hi32-app-style.png $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/style.png
	$(INSTALL_DATA) $(srcdir)/hi48-app-background.png $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/background.png
	$(INSTALL_DATA) $(srcdir)/hi48-app-colors.png $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/colors.png
	$(INSTALL_DATA) $(srcdir)/hi48-app-fonts.png $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/fonts.png
	$(INSTALL_DATA) $(srcdir)/hi48-app-screensaver.png $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/screensaver.png
	$(INSTALL_DATA) $(srcdir)/hi48-app-style.png $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/style.png
	$(INSTALL_DATA) $(srcdir)/hi32-app-information.png $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/information.png
	$(INSTALL_DATA) $(srcdir)/hi32-app-kcmdevices.png $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/kcmdevices.png
	$(INSTALL_DATA) $(srcdir)/hi32-app-kcmmemory.png $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/kcmmemory.png
	$(INSTALL_DATA) $(srcdir)/hi32-app-kcmpartitions.png $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/kcmpartitions.png
	$(INSTALL_DATA) $(srcdir)/hi32-app-kcmpci.png $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/kcmpci.png
	$(INSTALL_DATA) $(srcdir)/hi32-app-kcmprocessor.png $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/kcmprocessor.png
	$(INSTALL_DATA) $(srcdir)/hi32-app-kcmscsi.png $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/kcmscsi.png
	$(INSTALL_DATA) $(srcdir)/hi32-app-kcmsound.png $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/kcmsound.png
	$(INSTALL_DATA) $(srcdir)/hi32-app-kcmx.png $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/kcmx.png
	$(INSTALL_DATA) $(srcdir)/hi48-app-kcmdevices.png $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/kcmdevices.png
	$(INSTALL_DATA) $(srcdir)/hi48-app-kcmmemory.png $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/kcmmemory.png
	$(INSTALL_DATA) $(srcdir)/hi48-app-kcmpartitions.png $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/kcmpartitions.png
	$(INSTALL_DATA) $(srcdir)/hi48-app-kcmpci.png $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/kcmpci.png
	$(INSTALL_DATA) $(srcdir)/hi48-app-kcmprocessor.png $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/kcmprocessor.png
	$(INSTALL_DATA) $(srcdir)/hi48-app-kcmscsi.png $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/kcmscsi.png
	$(INSTALL_DATA) $(srcdir)/hi32-app-locale.png $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/locale.png
	$(INSTALL_DATA) $(srcdir)/hi48-app-locale.png $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/locale.png
	$(INSTALL_DATA) $(srcdir)/hi32-app-buttons.png $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/buttons.png
	$(INSTALL_DATA) $(srcdir)/hi32-app-kcmkwm.png $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/kcmkwm.png
	$(INSTALL_DATA) $(srcdir)/hi32-app-titlebar.png $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/titlebar.png
	$(INSTALL_DATA) $(srcdir)/hi32-app-winprops.png $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/winprops.png
	$(INSTALL_DATA) $(srcdir)/hi48-app-buttons.png $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/buttons.png
	$(INSTALL_DATA) $(srcdir)/hi48-app-kcmkwm.png $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/kcmkwm.png
	$(INSTALL_DATA) $(srcdir)/hi48-app-titlebar.png $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/titlebar.png
	$(INSTALL_DATA) $(srcdir)/hi48-app-winprops.png $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/winprops.png
	$(INSTALL_DATA) $(srcdir)/hi32-app-mouse.png $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/mouse.png
	$(INSTALL_DATA) $(srcdir)/hi48-app-keyboard.png $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/keyboard.png
	$(INSTALL_DATA) $(srcdir)/hi48-app-mouse.png $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/mouse.png
	$(INSTALL_DATA) $(srcdir)/hi32-app-kdmconfig.png $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/kdmconfig.png
	$(INSTALL_DATA) $(srcdir)/hi48-app-kdmconfig.png $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/kdmconfig.png
	$(INSTALL_DATA) $(srcdir)/hi32-app-knotify.png $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/knotify.png
	$(INSTALL_DATA) $(srcdir)/hi48-app-knotify.png $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/knotify.png
	$(INSTALL_DATA) $(srcdir)/hi32-app-bell.png $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/bell.png
	$(INSTALL_DATA) $(srcdir)/hi32-app-kcmsyssound.png $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/kcmsyssound.png
	$(INSTALL_DATA) $(srcdir)/hi48-app-bell.png $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/bell.png
	$(INSTALL_DATA) $(srcdir)/hi48-app-kcmsyssound.png $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/kcmsyssound.png
	$(INSTALL_DATA) $(srcdir)/hi32-app-kthememgr.png $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/kthememgr.png
	$(INSTALL_DATA) $(srcdir)/hi48-app-kthememgr.png $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/kthememgr.png

uninstall-kde-icons:
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/icons.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/colors.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/password.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/icons.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/clock.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/password.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/clock.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/energy.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/fonts.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/screensaver.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/style.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/background.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/colors.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/fonts.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/screensaver.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/style.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/information.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/kcmdevices.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/kcmmemory.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/kcmpartitions.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/kcmpci.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/kcmprocessor.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/kcmscsi.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/kcmsound.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/kcmx.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/kcmdevices.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/kcmmemory.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/kcmpartitions.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/kcmpci.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/kcmprocessor.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/kcmscsi.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/locale.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/locale.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/buttons.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/kcmkwm.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/titlebar.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/winprops.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/buttons.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/kcmkwm.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/titlebar.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/winprops.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/mouse.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/keyboard.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/mouse.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/kdmconfig.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/kdmconfig.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/knotify.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/knotify.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/bell.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/kcmsyssound.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/bell.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/kcmsyssound.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/32x32/apps/kthememgr.png
	-rm -f $(DESTDIR)$(kde_icondir)/hicolor/48x48/apps/kthememgr.png

#>+ 5
force-reedit:
		cd $(top_srcdir) && $(AUTOMAKE) --gnu kcontrol/pics/hicolor/Makefile
	cd $(top_srcdir) && perl admin/am_edit kcontrol/pics/hicolor/Makefile.in


#>+ 2
final:
	$(MAKE) all-am
#>+ 3
cvs-clean:
	$(MAKE) -f $(top_srcdir)/admin/Makefile.common cvs-clean

#>+ 3
kde-rpo-clean:
	-rm -f *.rpo
