# - Try to find the  freetype
# Once done this will define
#
#  FREETYPE_FOUND - system has Fontconfig
#  FREETYPE_INCLUDE_DIR - the FONTCONFIG include directory
#  FREETYPE_LIBRARIES - Link these to use FREETYPE
#  FREETYPE_DEFINITIONS - Compiler switches required for using FREETYPE
#


FIND_PROGRAM(FREETYPECONFIG_EXECUTABLE NAMES freetype-config PATHS
   /usr/bin
   /usr/local/bin
   /opt/local/bin
)

#reset vars
set(FREETYPE_LIBRARIES)
set(FREETYPE_INCLUDE_DIR)


# if freetype-config has been found
IF(FREETYPECONFIG_EXECUTABLE)

  EXEC_PROGRAM(${FREETYPECONFIG_EXECUTABLE} ARGS --libs RETURN_VALUE _return_VALUE OUTPUT_VARIABLE FREETYPE_LIBRARIES)

  EXEC_PROGRAM(${FREETYPECONFIG_EXECUTABLE} ARGS --cflags RETURN_VALUE _return_VALUE OUTPUT_VARIABLE FREETYPE_INCLUDE_DIR)
  IF(FREETYPE_LIBRARIES AND FREETYPE_INCLUDE_DIR)
    SET(FREETYPE_FOUND TRUE)
    message(STATUS "Found freetype: ${FREETYPE_LIBRARIES}")
  ENDIF(FREETYPE_LIBRARIES AND FREETYPE_INCLUDE_DIR)

  MARK_AS_ADVANCED(FREETYPE_LIBRARIES FREETYPE_INCLUDE_DIR)

ENDIF(FREETYPECONFIG_EXECUTABLE)
