
#!/usr/bin/env python
# Generated by pykdeuic4 from calendar.ui on Sun Sep 14 13:02:53 2008
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_calendar(object):
    def setupUi(self, calendar):
        calendar.setObjectName("calendar")
        calendar.resize(276, 255)
        self.vboxlayout = QtGui.QVBoxLayout(calendar)
        self.vboxlayout.setSpacing(0)
        self.vboxlayout.setMargin(0)
        self.vboxlayout.setObjectName("vboxlayout")
        self.kdatepicker = KDatePicker(calendar)
        self.kdatepicker.setAutoFillBackground(True)
        self.kdatepicker.setObjectName("kdatepicker")
        self.vboxlayout.addWidget(self.kdatepicker)

        self.retranslateUi(calendar)
        QtCore.QMetaObject.connectSlotsByName(calendar)

    def retranslateUi(self, calendar):
        pass

from PyKDE4.kdeui import KDatePicker
