[Desktop Entry]
Encoding=UTF-8
Type=XSession
Exec=${KDE4_BIN_INSTALL_DIR}/startkde
TryExec=${KDE4_BIN_INSTALL_DIR}/startkde
Name=KDE Plasma Workspace
Name[bg]=Работно пространство Plasma на KDE
Name[ca]=Espai de treball del Plasma del KDE
Name[cs]=Pracovní plocha Plasma
Name[da]=KDE Plasma arbejdsområde
Name[de]=KDE-Plasma-Arbeitsbereich
Name[es]=Espacio de trabajo Plasma de KDE
Name[et]=KDE Plasma töötsoon
Name[eu]=KDE Plasma langunea
Name[fi]=KDE Plasma-työtila
Name[he]=סביבת עבודה של KDE Plasma
Name[hu]=KDE Plasma munkaterület
Name[ia]=Spatio de labor de Plasma de KDE
Name[is]=KDE Plasma-vinnurými
Name[kk]=KDE Plasma жұмыс орны
Name[lt]=KDE Plasma darbastalio erdvė
Name[nb]=KDE Plasma arbeidsflate
Name[nds]=KDE-Arbeitrebeet Plasma
Name[nl]=KDE Plasma-werkruimte
Name[pt]=Área de Trabalho Plasma do KDE
Name[pt_BR]=Espaço de trabalho do Plasma do KDE
Name[ro]=Spațiu de lucru Plasma KDE
Name[ru]=Рабочий стол Plasma
Name[sr]=КДЕ‑ов плазма радни простор
Name[sr@ijekavian]=КДЕ‑ов плазма радни простор
Name[sr@ijekavianlatin]=KDE‑ov plasma radni prostor
Name[sr@latin]=KDE‑ov plasma radni prostor
Name[sv]=KDE Plasma arbetsyta
Name[ug]=ك د ئې(KDE) پلازما خىزمەت بوشلۇقى
Name[uk]=Робочий простір Плазми KDE
Name[x-test]=xxKDE Plasma Workspacexx
Name[zh_TW]=KDE Plasma 工作空間
Comment=The desktop made by KDE
Comment[bg]=Настолна среда KDE
Comment[ca]=L'escriptori creat pel KDE
Comment[cs]=Prostředí od KDE
Comment[da]=Skrivebordet fra KDE
Comment[de]=Die von KDE erstellte Arbeitsfläche
Comment[es]=El escritorio diseñado por KDE
Comment[et]=KDE loodud töölaud
Comment[eu]=KDE-k eginiko mahaigaina
Comment[fi]=KDE:n tekemä työpöytä
Comment[he]=שולחן העבודה של KDE
Comment[hr]=Radna površina koju je napravio KDE
Comment[hu]=A KDE által készített munkaasztal
Comment[ia]=Le scriptorio facite per KDE
Comment[is]=KDE Skjáborð
Comment[kk]=KDE үстелі
Comment[lt]=Darbastalis sukurtas su KDE
Comment[nb]=Skrivebordet som KDE laget
Comment[nds]=KDE-Schriefdisch
Comment[nl]=Het bureaublad gemaakt door KDE
Comment[pt]=O ambiente de trabalho feito pelo KDE
Comment[pt_BR]=O ambiente de trabalho feito pelo KDE
Comment[ro]=Biroul creat de KDE
Comment[ru]=Окружение рабочего стола от команды KDE
Comment[sr]=Радна површ у изведби КДЕ‑а
Comment[sr@ijekavian]=Радна површ у изведби КДЕ‑а
Comment[sr@ijekavianlatin]=Radna površ u izvedbi KDE‑a
Comment[sr@latin]=Radna površ u izvedbi KDE‑a
Comment[sv]=Skrivbordet skapat av KDE
Comment[ug]=بۇ ئۈستەلئۈستى KDE دا ياسالغان
Comment[uk]=Стільниця, створена командою KDE
Comment[x-test]=xxThe desktop made by KDExx
Comment[zh_TW]=KDE 製作的桌面
