[Desktop Entry]
Encoding=UTF-8
Type=XSession
Exec=${KDE4_BIN_INSTALL_DIR}/startkde --failsafe
TryExec=${KDE4_BIN_INSTALL_DIR}/startkde
Name=KDE Plasma Workspace (failsafe session)
Name[ca]=Espai de treball del Plasma del KDE (sessió a prova de fallades)
Name[es]=Espacio de trabajo Plasma de KDE (sesión a prueba de fallos)
Name[fi]=KDE Plasma-työtila (vikasietoinen istunto)
Name[he]=סביבת עבודה של KDE Plasma (הפעלה בטוחה)
Name[hr]=KDE Plasma Workspace (sigurnosna sesija)
Name[kk]=KDE Plasma жұмыс орны (қауіпсіз сеанс)
Name[lt]=KDE Plasma darbastalio erdvė (saugus seansas)
Name[nb]=KDE Plasma arbeidsflate (sikker økt)
Name[nl]=KDE Plasma-werkruimte (sessie met veilig mislukken)
Name[pt]=Área de Trabalho Plasma do KDE (sessão de recurso)
Name[pt_BR]=Espaço de trabalho do Plasma do KDE (sessão segura)
Name[ro]=Spațiu de lucru Plasma KDE (sesiune robustă)
Name[sv]=KDE Plasma arbetsyta (felsäker session)
Name[uk]=Робочий простір Плазми KDE (безпечний сеанс)
Name[x-test]=xxKDE Plasma Workspace (failsafe session)xx
Comment=The desktop made by KDE (failsafe session)
Comment[ca]=L'escriptori creat pel KDE (sessió a prova de fallades)
Comment[es]=El escritorio diseñado por KDE (sesión a prueba de fallos)
Comment[fi]=KDE:n tekemä työpöytä (vikasietoinen istunto)
Comment[he]=שולחן העבודה של KDE (הפעלה בטוחה)
Comment[hr]=Radna površina koju je napravio KDE (sigurnosna sesija)
Comment[kk]=KDE үстелі (қаупсіз сеанс)
Comment[lt]=Darbastalis sukurtas su KDE (saugus seansas)
Comment[nb]=Skrivebordet som KDE laget (sikker økt)
Comment[nl]=Het bureaublad gemaakt door KDE (sessie met veilig mislukken)
Comment[pt]=O ambiente de trabalho feito pelo KDE (sessão de recurso)
Comment[pt_BR]=O ambiente de trabalho feito pelo KDE (sessão segura)
Comment[ro]=Biroul creat de KDE (sesiune robustă)
Comment[sv]=Skrivbordet skapat av KDE (felsäker session)
Comment[uk]=Стільниця, створена командою KDE (безпечний сеанс)
Comment[x-test]=xxThe desktop made by KDE (failsafe session)xx
