[Desktop Entry]
Encoding=UTF-8
Type=XSession
Exec=${KDE4_BIN_INSTALL_DIR}/startkde
TryExec=${KDE4_BIN_INSTALL_DIR}/startkde
Name=KDE Plasma Workspace
Name[he]=סביבת עבודה של KDE Plasma
Name[kk]=KDE Plasma жұмыс орны
Name[nb]=KDE Plasma arbeidsflate
Name[nl]=KDE Plasma-werkruimte
Name[pt]=Área de Trabalho Plasma do KDE
Name[pt_BR]=Espaço de trabalho do Plasma do KDE
Name[ro]=Spațiu de lucru Plasma KDE
Name[sv]=KDE Plasma arbetsyta
Name[uk]=Робочий простір Плазми KDE
Name[x-test]=xxKDE Plasma Workspacexx
Comment=The desktop made by KDE
Comment[he]=שולחן העבודה של KDE
Comment[hr]=Radna površina koju je napravio KDE
Comment[kk]=KDE үстелі
Comment[nb]=Skrivebordet som KDE laget
Comment[nl]=Het bureaublad gemaakt door KDE
Comment[pt]=O ambiente de trabalho feito pelo KDE
Comment[pt_BR]=O ambiente de trabalho feito pelo KDE
Comment[ro]=Biroul creat de KDE
Comment[sv]=Skrivbordet skapat av KDE
Comment[uk]=Стільниця, створена командою KDE
Comment[x-test]=xxThe desktop made by KDExx
