[Desktop Entry]
Encoding=UTF-8
Type=XSession
Exec=${KDE4_BIN_INSTALL_DIR}/startkde --failsafe
TryExec=${KDE4_BIN_INSTALL_DIR}/startkde
Name=KDE Plasma Workspace (failsafe session)
Name[he]=סביבת עבודה של KDE Plasma (הפעלה בטוחה)
Name[nl]=KDE Plasma-werkruimte (sessie met veilig mislukken)
Name[pt_BR]=Espaço de trabalho do Plasma do KDE (sessão segura)
Name[ro]=Spațiu de lucru Plasma KDE (sesiune robustă)
Name[sv]=KDE Plasma arbetsyta (felsäker session)
Name[uk]=Робочий простір Плазми KDE (безпечний сеанс)
Name[x-test]=xxKDE Plasma Workspace (failsafe session)xx
Comment=The desktop made by KDE (failsafe session)
Comment[he]=שולחן העבודה של KDE (הפעלה בטוחה)
Comment[nl]=Het bureaublad gemaakt door KDE (sessie met veilig mislukken)
Comment[pt_BR]=O ambiente de trabalho feito pelo KDE (sessão segura)
Comment[ro]=Biroul creat de KDE (sesiune robustă)
Comment[sv]=Skrivbordet skapat av KDE (felsäker session)
Comment[uk]=Стільниця, створена командою KDE (безпечний сеанс)
Comment[x-test]=xxThe desktop made by KDE (failsafe session)xx
