[Desktop Entry]
Encoding=UTF-8
Type=XSession
Exec=${KDE4_BIN_INSTALL_DIR}/startkde
TryExec=${KDE4_BIN_INSTALL_DIR}/startkde
Name=KDE
Name[hi]=केडीई
Name[mn]=КДЭ
Name[ta]=Kஏற்றக் காவலன்
Name[xh]=iKDE
Name[xx]=xxKDExx
Comment=The K Desktop Environment. A powerful Open Source graphical desktop environment
Comment[bs]=K Desktop Environment. Moćan grafički desktop otvorenog izvornog koda
Comment[ca]=L'entorn d'escriptori K. Un poderós entorn d'escriptori gràfic de Codi Font Obert
Comment[cy]=Yr Amgylchedd Penbwrdd K.  Amgylchedd penbwrdd graffegol pwerus, sy'n gôd-agored.
Comment[da]=K Skrivebordsmiljøet. Et kraftigt, åbent, grafisk skrivebordsmiljø
Comment[de]=Das K Desktop Environment. Eine mächtige, graphische Arbeitsumgebung und Open Source / Freie Software
Comment[el]=Το K Desktop Environment. Ένα πανίσχυρο ελεύθερης προέλευσης γραφικό περιβάλλον επιφάνειας εργασίας
Comment[es]=El Entorno de Escritorio K, un potente entorno de escritorio gráfico realizado de código abierto
Comment[et]=K töölaua keskkond on võimas vaba tarkvara graafiline töölaua keskkond
Comment[fi]=KDE-työpöytäympäristö (K Desktop Environment) on tehokas avoimen lähdekoodin graafinen työpöytäympäristö
Comment[fr]=The K Desktop Environment. Un environnement de bureau graphique, puissant et Open Source
Comment[he]=The K Desktop Environment. סביבת עבודה גרפית, בעלת-עוצמה בקוד פתוח
Comment[hi]=के डेस्कटॉप वातावरण. एक शक्तिशाली, ओपन सोर्स चित्रमय डेस्कटॉप वातावरण
Comment[hu]=A KDE grafikus munkakörnyezet, egy szabad forráskódú grafikus ablakkezelő környezet
Comment[it]=L'ambiente desktop KDE. Un potente ambiente desktop grafico Open Source
Comment[mn]=The K Desktop Environment. Хүчирхэг нээлттэй эх код бүхий график дэлгэцийн орчин
Comment[nb]=K Desktop Environment. Et kraftig grafisk skrivebordsmiljø med åpen kildekode.
Comment[nl]=De K Desktop Environment, een krachtige open source grafische desktop environment
Comment[nn]=K Desktop Environment. Eit kraftig grafisk skrivebordsmiljø med open kjeldekode.
Comment[pl]=Środowisko KDE. Potężne środowisko graficzne Wolnego Oprogramowania.
Comment[pt]=O K Desktop Environment. Um ambiente gráfico open source poderoso
Comment[pt_BR]=Acrônimo para K Desktop Environment (ou Ambiente de Trabalho K). Um poderoso ambiente de trabalho gráfico de código aberto
Comment[ro]=K Desktop Environment. Un mediu grafic cu surse deschise, foarte puternic
Comment[sk]=The K Desktop Environment. Výkonné, voľne šíriteľné grafické pracovné prostredie
Comment[sl]=Namizno okolje K. Zmogljivo grafično namizno okolje odprte kode
Comment[sr]=K Desktop Environment (KDE). Моћно графичко радно окружење отвореног кода
Comment[sv]=K-skrivbordsmiljön. En kraftfull grafisk skrivbordsmiljö med öppen källkod
Comment[ta]= Kமேல்மேசை சூழல். சக்திவாய்ந்த திறந்த ஆணைமூல சித்திர வகை மேல்மேசை சூழல்
Comment[tr]=KDE Masaüstü Yöneticisi. Güçlü bir grafiksel masaüstü ortamı
Comment[uk]=The K Desktop Environment. Потужне графічне середовище з відкритими текстами
Comment[uz]=KDE (K Desktop Environment) - кучли Open Source график иш столи муҳити
Comment[vi]=môi trường desktop K, môi trường desktop đồ hoạ mã nguồn mở rất mạnh
Comment[xx]=xxThe K Desktop Environment. A powerful Open Source graphical desktop environmentxx
Comment[zh_CN]=K 桌面环境。强大的开放源代码图形桌面环境
